var floorMap = [
  {
    "roomFacilityTypeID": 2,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 1,
    "roomId": 705,
    "roomName": "PTK1-705",
    "roomTypeID": 1,
    "availabilityTimeInMinutes": 498,
    "capacity": 13,
    "availabilityTime": "8 hr 18 min",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "PTK1-705",
    "roomFacilityTypeName": "Public",
    "statusName": "AVAILABLE",
    "isVideoEnabled": "YES",
    "startTime": "",
    "currentRoomAvailabilityStatus": 1,
    "endTime": "",
    "roomType": "MeetingRoom"
  },
  {
    "roomFacilityTypeID": 2,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 1,
    "roomId": 706,
    "roomName": "PTK1-706",
    "roomTypeID": 1,
    "availabilityTimeInMinutes": 498,
    "capacity": 13,
    "availabilityTime": "8 hr 18 min",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "PTK1-706",
    "roomFacilityTypeName": "Public",
    "statusName": "AVAILABLE",
    "isVideoEnabled": "NO",
    "startTime": "",
    "currentRoomAvailabilityStatus": 1,
    "endTime": "",
    "roomType": "MeetingRoom"
  },
  {
    "roomFacilityTypeID": 2,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 1,
    "roomId": 707,
    "roomName": "PTK1-707",
    "roomTypeID": 1,
    "availabilityTimeInMinutes": 498,
    "capacity": 9,
    "availabilityTime": "8 hr 18 min",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "PTK1-707",
    "roomFacilityTypeName": "Public",
    "statusName": "AVAILABLE",
    "isVideoEnabled": "NO",
    "startTime": "",
    "currentRoomAvailabilityStatus": 1,
    "endTime": "",
    "roomType": "MeetingRoom"
  },
  {
    "roomFacilityTypeID": 2,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 4,
    "roomId": 709,
    "roomName": "PTK1-709",
    "roomTypeID": 1,
    "availabilityTimeInMinutes": 0,
    "capacity": 13,
    "availabilityTime": "-",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "PTK1-709",
    "roomFacilityTypeName": "Public",
    "statusName": "OCCUPIED",
    "isVideoEnabled": "YES",
    "startTime": "",
    "currentRoomAvailabilityStatus": 4,
    "endTime": "",
    "roomType": "MeetingRoom"
  },
  {
    "roomFacilityTypeID": 2,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 4,
    "roomId": 710,
    "roomName": "PTK1-710",
    "roomTypeID": 1,
    "availabilityTimeInMinutes": 0,
    "capacity": 13,
    "availabilityTime": "-",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "PTK1-710",
    "roomFacilityTypeName": "Public",
    "statusName": "OCCUPIED",
    "isVideoEnabled": "NO",
    "startTime": "",
    "currentRoomAvailabilityStatus": 4,
    "endTime": "",
    "roomType": "MeetingRoom"
  },
  {
    "roomFacilityTypeID": 0,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 4,
    "roomId": 723,
    "roomName": "COLLAB 7E#1",
    "availabilityTimeInMinutes": 0,
    "roomTypeID": 2,
    "capacity": 4,
    "availabilityTime": "-",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "COLLAB7E1",
    "roomFacilityTypeName": "",
    "statusName": "OCCUPIED",
    "isVideoEnabled": 0,
    "currentRoomAvailabilityStatus": 4,
    "startTime": "",
    "endTime": "",
    "roomType": "CollaborationRoom"
  },
  {
    "roomFacilityTypeID": 0,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 4,
    "roomId": 724,
    "roomName": "COLLAB 7E#2",
    "availabilityTimeInMinutes": 0,
    "roomTypeID": 2,
    "capacity": 4,
    "availabilityTime": "-",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "COLLAB7E2",
    "roomFacilityTypeName": "",
    "statusName": "OCCUPIED",
    "isVideoEnabled": 0,
    "currentRoomAvailabilityStatus": 4,
    "startTime": "",
    "endTime": "",
    "roomType": "CollaborationRoom"
  },
  {
    "roomFacilityTypeID": 0,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 4,
    "roomId": 726,
    "roomName": "COLLAB 7G#1",
    "availabilityTimeInMinutes": 0,
    "roomTypeID": 2,
    "capacity": 4,
    "availabilityTime": "-",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "COLLAB7G1",
    "roomFacilityTypeName": "",
    "statusName": "OCCUPIED",
    "isVideoEnabled": 0,
    "currentRoomAvailabilityStatus": 4,
    "startTime": "",
    "endTime": "",
    "roomType": "CollaborationRoom"
  },
  {
    "roomFacilityTypeID": 0,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 4,
    "roomId": 727,
    "roomName": "COLLAB 7G#2",
    "availabilityTimeInMinutes": 0,
    "roomTypeID": 2,
    "capacity": 4,
    "availabilityTime": "-",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "COLLAB7G2",
    "roomFacilityTypeName": "",
    "statusName": "OCCUPIED",
    "isVideoEnabled": 0,
    "currentRoomAvailabilityStatus": 4,
    "startTime": "",
    "endTime": "",
    "roomType": "CollaborationRoom"
  },
  {
    "roomFacilityTypeID": 0,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 1,
    "roomId": 728,
    "roomName": "COLLAB 7G#3",
    "availabilityTimeInMinutes": 0,
    "roomTypeID": 2,
    "capacity": 4,
    "availabilityTime": "-",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "COLLAB7G3",
    "roomFacilityTypeName": "",
    "statusName": "AVAILABLE",
    "isVideoEnabled": 0,
    "currentRoomAvailabilityStatus": 1,
    "startTime": "",
    "endTime": "",
    "roomType": "CollaborationRoom"
  }
]



var facilities = [
  {
      "floorId": 7,
      "roomId": 751,
      "roomName": "Printer West"
  },
  {
      "floorId": 7,
      "roomId": 752,
      "roomName": "Toilet West"
  },
  {
      "roomId": 7,
      "facilityId": 753,
      "roomName": "Toilet East"
  }

]



var people = [
  {
    "roomId": 74,
    "buildingName": "PTK1",
    "deskDisplayName": "Desk G7-18",
    "roomName": "Gowtham Vijayakumar",
    "imageURL": "https://ptk1storageac.blob.core.windows.net/ptk1images/default_userAvatar-300DPI.PNG",
    "floorDisplayName": "Floor 7",
    "department": "EGI",
    "deskNumber": "G7-18",
    "currentLocation": "Not Available"
  },
  {
    "roomId": 75,
    "buildingName": "PTK1",
    "deskDisplayName": "Desk G7-17",
    "roomName": "Avi Amon",
    "imageURL": "https://ptk1storageac.blob.core.windows.net/ptk1images/default_userAvatar-300DPI.PNG",
    "floorDisplayName": "Floor 7",
    "department": "EGI",
    "deskNumber": "G7-17",
    "currentLocation": "Not Available"
  }

]


var openRoom = [
  {
    "roomFacilityTypeID": 2,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 1,
    "roomId": 705,
    "roomName": "PTK1-705",
    "roomTypeID": 1,
    "availabilityTimeInMinutes": 498,
    "capacity": 13,
    "availabilityTime": "8 hr 18 min",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "PTK1-705",
    "roomFacilityTypeName": "Public",
    "statusName": "AVAILABLE",
    "isVideoEnabled": "YES",
    "startTime": "",
    "currentRoomAvailabilityStatus": 1,
    "endTime": "",
    "roomType": "MeetingRoom"
  },
  {
    "roomFacilityTypeID": 2,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 1,
    "roomId": 706,
    "roomName": "PTK1-706",
    "roomTypeID": 1,
    "availabilityTimeInMinutes": 498,
    "capacity": 13,
    "availabilityTime": "8 hr 18 min",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "PTK1-706",
    "roomFacilityTypeName": "Public",
    "statusName": "AVAILABLE",
    "isVideoEnabled": "NO",
    "startTime": "",
    "currentRoomAvailabilityStatus": 1,
    "endTime": "",
    "roomType": "MeetingRoom"
  },
  {
    "roomFacilityTypeID": 2,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 1,
    "roomId": 707,
    "roomName": "PTK1-707",
    "roomTypeID": 1,
    "availabilityTimeInMinutes": 498,
    "capacity": 9,
    "availabilityTime": "8 hr 18 min",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "PTK1-707",
    "roomFacilityTypeName": "Public",
    "statusName": "AVAILABLE",
    "isVideoEnabled": "NO",
    "startTime": "",
    "currentRoomAvailabilityStatus": 1,
    "endTime": "",
    "roomType": "MeetingRoom"
  },
  {
    "roomFacilityTypeID": 2,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 4,
    "roomId": 709,
    "roomName": "PTK1-709",
    "roomTypeID": 1,
    "availabilityTimeInMinutes": 0,
    "capacity": 13,
    "availabilityTime": "-",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "PTK1-709",
    "roomFacilityTypeName": "Public",
    "statusName": "OCCUPIED",
    "isVideoEnabled": "YES",
    "startTime": "",
    "currentRoomAvailabilityStatus": 4,
    "endTime": "",
    "roomType": "MeetingRoom"
  },
  {
    "roomFacilityTypeID": 2,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 4,
    "roomId": 710,
    "roomName": "PTK1-710",
    "roomTypeID": 1,
    "availabilityTimeInMinutes": 0,
    "capacity": 13,
    "availabilityTime": "-",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "PTK1-710",
    "roomFacilityTypeName": "Public",
    "statusName": "OCCUPIED",
    "isVideoEnabled": "NO",
    "startTime": "",
    "currentRoomAvailabilityStatus": 4,
    "endTime": "",
    "roomType": "MeetingRoom"
  },
  {
    "roomFacilityTypeID": 0,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 4,
    "roomId": 723,
    "roomName": "COLLAB 7E#1",
    "availabilityTimeInMinutes": 0,
    "roomTypeID": 2,
    "capacity": 4,
    "availabilityTime": "-",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "COLLAB7E1",
    "roomFacilityTypeName": "",
    "statusName": "OCCUPIED",
    "isVideoEnabled": 0,
    "currentRoomAvailabilityStatus": 4,
    "startTime": "",
    "endTime": "",
    "roomType": "CollaborationRoom"
  },
  {
    "roomFacilityTypeID": 0,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 4,
    "roomId": 724,
    "roomName": "COLLAB 7E#2",
    "availabilityTimeInMinutes": 0,
    "roomTypeID": 2,
    "capacity": 4,
    "availabilityTime": "-",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "COLLAB7E2",
    "roomFacilityTypeName": "",
    "statusName": "OCCUPIED",
    "isVideoEnabled": 0,
    "currentRoomAvailabilityStatus": 4,
    "startTime": "",
    "endTime": "",
    "roomType": "CollaborationRoom"
  },
  {
    "roomFacilityTypeID": 0,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 4,
    "roomId": 726,
    "roomName": "COLLAB 7G#1",
    "availabilityTimeInMinutes": 0,
    "roomTypeID": 2,
    "capacity": 4,
    "availabilityTime": "-",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "COLLAB7G1",
    "roomFacilityTypeName": "",
    "statusName": "OCCUPIED",
    "isVideoEnabled": 0,
    "currentRoomAvailabilityStatus": 4,
    "startTime": "",
    "endTime": "",
    "roomType": "CollaborationRoom"
  },
  {
    "roomFacilityTypeID": 0,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 4,
    "roomId": 727,
    "roomName": "COLLAB 7G#2",
    "availabilityTimeInMinutes": 0,
    "roomTypeID": 2,
    "capacity": 4,
    "availabilityTime": "-",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "COLLAB7G2",
    "roomFacilityTypeName": "",
    "statusName": "OCCUPIED",
    "isVideoEnabled": 0,
    "currentRoomAvailabilityStatus": 4,
    "startTime": "",
    "endTime": "",
    "roomType": "CollaborationRoom"
  },
  {
    "roomFacilityTypeID": 0,
    "displayName": "",
    "buildingAndFloorName": "PTK1, Floor 7",
    "currentRoomAvailabilityStatusIcon": 1,
    "roomId": 728,
    "roomName": "COLLAB 7G#3",
    "availabilityTimeInMinutes": 0,
    "roomTypeID": 2,
    "capacity": 4,
    "availabilityTime": "-",
    "floorId": 7,
    "currentTime": "2022-09-15 15:41:38",
    "entityName": "COLLAB7G3",
    "roomFacilityTypeName": "",
    "statusName": "AVAILABLE",
    "isVideoEnabled": 0,
    "currentRoomAvailabilityStatus": 1,
    "startTime": "",
    "endTime": "",
    "roomType": "CollaborationRoom"
  }
]
